# Generated by Django 5.1.3 on 2024-12-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='sold_count',
        ),
    ]
